### ISSUE TITLE
Self-checkout, adjust quantity

### ISSUE THREAD

**Issue by mazgor** [tobiaszimmermann1/foodcoop-plugin#32]
The entry of decimal places with 'point' does not work. For example, if I enter 1.5, the shopping basket simply shows 1 afterwards (an error message appears with 'comma').

And the input field looks a little out of place, the title 'Quantity' is slightly in the field and the numbers entered are not displayed. Both in Safari and Chrome.

Also, when you click in the input field to adjust the quantity, it would be cool if (1) a number block appeared directly and (2) the input field was a little less wide, currently it zooms in a little when you enter a number and then when you click on 'Apply quantity' and get back to the shopping basket, the zoom is wrong there too and you have to zoom out again first to see everything. 

![IMG_6731](https://github.com/tobiaszimmermann1/foodcoop-plugin/assets/35103175/aa843552-9393-4870-9caa-243a96dd3096)

**Comment by tobiaszimmermann1** [comment]
should be fixed with v 1.7.4
