### ISSUE TITLE
Regular woocommerce purchase does not work, if a collective order is pending

### ISSUE THREAD

**Issue by mazgor** [tobiaszimmermann1/foodcoop-plugin#33]
If there is a pending collective order, you can't place a regular woo commerce order and pay with your Foodcoop wallet. If you do, the plugin will either credit or debit you the difference to the already placed collective order. So I have a pending collective order for CHF 1.92, I want to place a regular woocommerce order for CHF 6.36 and pay with my Foodcoop wallet, I only get debited for CHF 4.44 and in the process the collective order gets deleted / is lost.

![Bildschirmfoto 2024-01-24 um 14 04 50](https://github.com/tobiaszimmermann1/foodcoop-plugin/assets/35103175/3e9ab6db-8288-4080-a312-702b194564be)

![Bildschirmfoto 2024-01-24 um 14 07 04](https://github.com/tobiaszimmermann1/foodcoop-plugin/assets/35103175/b0a4af72-4b27-4a53-b4f5-57ce62ac24eb)

![Bildschirmfoto 2024-01-24 um 14 09 55](https://github.com/tobiaszimmermann1/foodcoop-plugin/assets/35103175/879e7148-5d25-40af-ac27-9868b06c6664)

**Comment by tobiaszimmermann1** [comment]
should be fixed with v 1.7.4
